import type { Metadata } from "next";
import {  Nunito } from "next/font/google";

import "./globals.css";
import Layout from "@/components/layout/Layout";
import NextTopLoader from "nextjs-toploader";
import { ClerkProvider, auth } from "@clerk/nextjs";
const nunito = Nunito({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { userId } = auth();
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={nunito.className}>
          <NextTopLoader
            height={2}
            color="#27AE60"
            easing="cubic-bezier(0.53,0.21,0,1)"
          />
          {userId ? <Layout>{children}</Layout> : <>{children}</>}
        </body>
      </html>
    </ClerkProvider>
  );
}
